name: Build, Tag, and Publish Docker image
env:
  REGISTRY: docker.pkg.github.com
  IMAGE: webhooks

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build, Tag, and Publish Docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Generate VERSION
        run: echo "::set-env name=VERSION::$(git describe --tags --always --dirty)"
      - name: Build
        run: docker build -t ${REGISTRY}/${GITHUB_REPOSITORY}/${IMAGE}:${VERSION} .
      - name: Tag
        run: docker tag ${REGISTRY}/${GITHUB_REPOSITORY}/${IMAGE}:${VERSION} ${REGISTRY}/${GITHUB_REPOSITORY}/${IMAGE}:latest
      - name: Login to Registry
        run: echo ${{ secrets.GITHUB_DOCKER_PASSWORD }} | docker login ${REGISTRY} -u ${{ secrets.GITHUB_DOCKER_USERNAME }} --password-stdin
      - name: Publish
        run: |
          docker push ${REGISTRY}/${GITHUB_REPOSITORY}/${IMAGE}:${VERSION}
          docker push ${REGISTRY}/${GITHUB_REPOSITORY}/${IMAGE}:latest
  # experiment:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v1
  #     - run: echo "::set-env name=VERSION::$(git describe --tags --always --dirty)"
  #     - run: echo ${REGISTRY}/${GITHUB_REPOSITORY}/${REPOSITORY}:${VERSION}
