name: Build, Tag, and Publish Docker image
env:
  REGISTRY: docker.pkg.github.com
  IMAGE: webhooks

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build, Tag, and Publish Docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Generate VERSION
        run: echo "::set-env name=VERSION::$(git describe --tags --always --dirty)"
      - name: Build IMAGE
        run: docker build -t ${IMAGE} .
      - name: Tag IMAGE:VERSION and IMAGE:latest
        run: |
          docker tag ${IMAGE} ${REGISTRY}/${{ github.repository }}/${IMAGE}:${VERSION}
          docker tag ${IMAGE} ${REGISTRY}/${{ github.repository }}/${IMAGE}:latest
      - name: Login to Registry
        run: echo ${{ secrets.GITHUB_DOCKER_PASSWORD }} | docker login ${REGISTRY} -u ${{ secrets.GITHUB_DOCKER_USERNAME }} --password-stdin
      - name: Publish IMAGE:VERSION and IMAGE:latest
        run: |
          docker push ${REGISTRY}/${GITHUB_REPOSITORY}/${IMAGE}:${VERSION}
          docker push ${REGISTRY}/${GITHUB_REPOSITORY}/${IMAGE}:latest
      # - name: Create Deployment - IMAGE:VERSION to staging
      #   uses: ./.github/actions/create-deployment
      #   with:
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     payload: ${{ env.VERSION }}
      #     description: Deploy ${{ env.IMAGE }}:${{ env.VERSION }} to staging
